"use client";
import { useEffect, useState } from "react";
import { Button, Card, Input } from "../../../components/ui";
import { api } from "../../../lib/api";

export default function DineInPage() {
  const [branchId, setBranchId] = useState(""); const [tables,setTables]=useState<any[]>([]); const [stations,setStations]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [tableId, setTableId] = useState(""); const [stationId, setStationId] = useState(""); const [productId, setProductId] = useState(""); const [result, setResult] = useState(""); const [error,setError]=useState("");
  useEffect(()=>{api<any[]>("/branches").then(xs=>{setBranchId(xs[0]?.id??"")}).catch(e=>setError(e.message))},[]);
  useEffect(()=>{if(!branchId)return; Promise.all([api<any[]>(`/phase4/tables?branchId=${branchId}`),api<any[]>(`/phase4/stations?branchId=${branchId}`),api<any[]>(`/pos/catalog?branchId=${branchId}`)]).then(([t,s,p])=>{setTables(t);setStations(s);setProducts(p);setTableId(t[0]?.id??"");setStationId(s[0]?.id??"");setProductId(p[0]?.id??"")}).catch(e=>setError(e.message))},[branchId]);
  async function open() { const data = await api<any>("/phase4/dine-in/orders", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ branchId, tableId, stationId, items: [{ productId, quantity: 1 }] }) }); setResult(`Order ${data.order?.orderNumber ?? data.order?.id} sent to kitchen`); }
  return <main className="mx-auto max-w-2xl space-y-4 p-6"><h1 className="text-2xl font-semibold">Dine-in waiter</h1><Card><div className="grid gap-3"><label>Branch<select value={branchId} onChange={e=>setBranchId(e.target.value)}><option value="">Select branch</option>{branchId&&<option value={branchId}>{branchId}</option>}</select></label><label>Table<select value={tableId} onChange={e=>setTableId(e.target.value)}>{tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Kitchen station<select value={stationId} onChange={e=>setStationId(e.target.value)}>{stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Menu item<select value={productId} onChange={e=>setProductId(e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Button disabled={!tableId||!productId} onClick={open}>Send dine-in order</Button>{!tables.length&&branchId&&<p>Loading available tables and menu…</p>}{error&&<p role="alert">{error}</p>}{result && <p role="status">{result}</p>}</div></Card></main>;
}
