// Browser walkthrough for the Phase 3 menu/register/checkout/reprint path.
const { spawn } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");

async function main() {
  const profile = fs.mkdtempSync(path.join(os.tmpdir(), "cafe-phase3-browser-"));
  const browser = spawn(process.env.CHROME_PATH || "C:/Program Files/Google/Chrome/Application/chrome.exe", ["--headless", "--disable-gpu", "--remote-debugging-port=0", `--user-data-dir=${profile}`, "about:blank"], { windowsHide: true, stdio: ["ignore", "ignore", "pipe"] });
  try {
    const endpoint = await new Promise((resolve, reject) => { let output = ""; const timer = setTimeout(() => reject(new Error("Chrome startup timeout")), 20000); browser.on("error", reject); browser.stderr.on("data", chunk => { output += chunk; const found = output.match(/DevTools listening on (ws:\/\/[^\s]+)/); if (found) { clearTimeout(timer); resolve(found[1]); } }); });
    const pages = await (await fetch(`http://${new URL(endpoint).host}/json/list`)).json(); const socket = new WebSocket(pages.find(p => p.type === "page").webSocketDebuggerUrl); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; });
    let sequence = 0; const pending = new Map(); socket.onmessage = ({ data }) => { const message = JSON.parse(data); const call = pending.get(message.id); if (!call) return; pending.delete(message.id); message.error ? call.reject(message.error) : call.resolve(message.result); };
    const send = (method, params = {}) => new Promise((resolve, reject) => { const id = ++sequence; const timer = setTimeout(() => reject(new Error(`${method} timed out`)), 60000); pending.set(id, { resolve, reject, timer }); socket.send(JSON.stringify({ id, method, params })); });
    const evaluate = async expression => { const result = await send("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description || result.exceptionDetails.text); return result.result?.value; };
    const waitFor = async expression => { for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await new Promise(r => setTimeout(r, 300)); } throw new Error(`Browser condition timed out: ${expression}`); };
    await send("Page.enable");
    await send("Page.navigate", { url: "http://localhost:3000/login" }); await waitFor('Boolean(document.querySelector("body"))');
    await evaluate(`(()=>{const original=window.fetch.bind(window);window.fetch=(input,init={})=>{const url=String(input);if(url.includes('/pos/orders')&&init.method==='POST'){init.headers={...(init.headers||{}),'idempotency-key':crypto.randomUUID()};}return original(input,init);};})()`);
    const fixture = await evaluate(`(async()=>{const call=async(path,body,csrf)=>{const r=await fetch('/api/v1'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(csrf?{'x-csrf-token':csrf}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(JSON.stringify(d));return d;};const platform=await call('/platform/auth/login',{email:${JSON.stringify(process.env.SEED_ADMIN_EMAIL || "admin@example.test")},password:${JSON.stringify(process.env.SEED_ADMIN_PASSWORD || "ChangeMe123!")}});const catalog=await call('/platform/catalog');const suffix=crypto.randomUUID().slice(0,8);const password='Browser-Phase3-2026!';const org=await call('/platform/organizations',{name:'Phase 3 Browser Cafe '+suffix,businessType:'CAFE',email:'phase3-browser-'+suffix+'@example.test',phone:'03001234567',ownerName:'Browser Owner',ownerUsername:'phase3-browser-'+suffix,temporaryPassword:password,planId:catalog.plans[0].id,initialBranchName:'Main Branch',timezone:'Asia/Karachi',currencyCode:'PKR',graceDays:0,moduleIds:[]},platform.csrfToken);let login=await call('/auth/login',{identifier:'phase3-browser-'+suffix,password});await call('/auth/change-temporary-password',{currentPassword:password,newPassword:password+'New'},login.csrfToken);login=await call('/auth/login',{identifier:'phase3-browser-'+suffix,password:password+'New'});sessionStorage.setItem('csrf',login.csrfToken);const branches=await call('/branches');const branchId=branches[0].id;const product=await call('/pos/products',{name:'Browser Latte',taxRateBps:1000,modifierConfig:[{id:'oat',name:'Oat milk',priceMinor:100,active:true}],prices:[{branchId,priceMinor:1000}]},login.csrfToken);const register=await call('/pos/registers/open',{branchId,openingFloatMinor:1000},login.csrfToken);const order=await call('/pos/orders',{branchId,registerId:register.id,items:[{productId:product.id,quantity:1,modifiers:[{id:'oat'}]}],payments:[{method:'CASH',amountMinor:1210}]},login.csrfToken);return {orderId:order.id};})()`);
    const output = path.join(process.cwd(), "docs", "phase-3", "screenshots"); fs.mkdirSync(output, { recursive: true });
    for (const [name, width, height] of [["desktop", 1366, 768], ["tablet", 1024, 768], ["mobile", 390, 844]]) { await send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: false }); await send("Page.navigate", { url: "http://localhost:3000/workspace/menu" }); await waitFor('Boolean(document.body) && document.body.innerText.includes("Menu management")'); const shot = await send("Page.captureScreenshot", { format: "png" }); fs.writeFileSync(path.join(output, `${name}-menu.png`), Buffer.from(shot.data, "base64")); await send("Page.navigate", { url: "http://localhost:3000/workspace/pos" }); await waitFor('Boolean(document.body) && document.body.innerText.includes("Point of sale")'); const posShot = await send("Page.captureScreenshot", { format: "png" }); fs.writeFileSync(path.join(output, `${name}-pos.png`), Buffer.from(posShot.data, "base64")); console.log(`${name}: menu and POS walkthrough rendered`); }
    await send("Page.navigate", { url: `http://localhost:3000/api/v1/pos/orders/${fixture.orderId}/receipt` }); await waitFor('Boolean(document.body) && document.body.innerText.includes("Browser Latte")'); const receiptShot = await send("Page.captureScreenshot", { format: "png" }); fs.writeFileSync(path.join(output, "desktop-receipt.png"), Buffer.from(receiptShot.data, "base64")); console.log("desktop: receipt reprint rendered"); socket.close();
  } finally { browser.kill(); }
}
main().catch(error => { console.error(error.stack || error); process.exitCode = 1; });
